apiVersion: v1
kind: Secret
metadata:
  name: prometheus
  namespace: grafana
  labels:
     grafana_datasource: "1"
type: Opaque
stringData:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        orgId: 1
        url: http://prometheus-kube-prometheus-prometheus.prometheus.svc.cluster.local:9090
        isDefault: true
        editable: true
        httpMethod: GET
