#This basic values file contains a example for each resource which can be created using this Chart
space:
  enabled: true
  spaces:
    - name: space-sample
      filepath: spaces/space-sample.json

indexLifecyclePolicy:
  enabled: true
  policies:
    - name: sample-policy
      filepath: indexLifecyclePolicy/sample-policy.json

indexTemplate:
  enabled: true
  templates:
    - name: indextemplate-sample
      filepath: indexTemplates/indextemplate-sample.json

index:
  enabled: true
  indeces:
    - name: index-sample
      dependencies:
        indexTemplates:
          - indextemplate-sample
        #indices:
        #  - index-base-sample
      filepath: index/index-sample.json


indexPattern:
  enabled: true
  patterns:
    - name: indexpattern-sample
      spacename: space-sample 
      #dependencies:
      #  - type: index-pattern
      #    name: indexpattern-base-sample
      filepath: indexPatterns/indexpattern-sample.json


savedSearch:
  enabled: true
  searches:
    - name: savedsearch-sample
      spacename:  space-sample
      dependencies:
        - type: index-pattern
          name: indexpattern-sample
      filepath: searches/savedsearch-sample.json


visualization:
  enabled: true
  visualizations:
    - name: visualization-sample
      spacename:  space-sample
      dependencies:
        - type: index-pattern
          name: indexpattern-sample
      filepath: visualizations/visualization-sample.json

lens:
  enabled: true
  lenses:
    - name: lens-sample
      spacename:  space-sample
      dependencies:
        - type: index-pattern
          name: indexpattern-sample
      filepath: lens/lens-sample.json


dashboard:
  enabled: true
  dashboards:
    - name: dashboard-sample
      spacename:  space-sample
      dependencies:
        - type: lens
          name: lens-sample
      filepath: dashboards/sample-dashboard.json

role:
  enabled: true
  roles:
    - name: elasticsearchrole-sample
      filepath: roles/elasticsearchrole-sample.json


user:
  enabled: true
  users:
    - name: elasticsearchuser-sample
      secretname: elasticsearchuser-secret
      password: dGVzdGVy
      filepath: users/elasticsearchuser-sample

