---
# Version of Kibana.
#
version: 8.4.1

licenseType: basic

# Labels that will be applied to Kibana.
#
labels: {}
  #appname: kibana
  # key: value

# Annotations that will be applied to Kibana.
#
annotations: {}
  # key: value

spec:
  # Count of Kibana replicas to create.
  #
  count: 1

  # Reference to ECK-managed Elasticsearch resource, ideally from {{ "elasticsearch.fullname" }}
  #
  elasticsearchRef:
    name: elastic-eck-elasticsearch
    # namespace: default
  http:
    service:
      spec:
        # Type of service to deploy for Kibana.
        # This deploys a load balancer in a cloud service provider, where supported.
        # 
        type: ClusterIP
        ports:
          - port: 5601
            targetPort: 5601
            protocol: TCP
            name: http
    #tls:
    #  certificate:
    #    secretName: kibana-tls-certificate


##service:
#  type: ClusterIP
#  port: 80
#
ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS  
    kubernetes.io/ingress.class: nginx
  rules:
    - host: kibana.berlindevops.com
      ingressPath: "/"
      serviceFullName: elastic-eck-kibana-kb-http
      servicePortNumber: 5601
  tls:
    - secretName: kibana.berlindevops.com-tls
      hosts:
        - kibana.berlindevops.com
  