apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: logs
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  topicName: logs
  partitions: 1
  replicas: 1
  config:
    retention.ms: 86000000
