apiVersion: v1
data:
  token: UXpoQ1d1M3JCVEwzWmJpYUZ0QTk=
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"token":"UXpoQ1d1M3JCVEwzWmJpYUZ0QTk="},"kind":"Secret","metadata":{"annotations":{},"name":"gitlab-access","namespace":"argo"},"type":"Opaque"}
  creationTimestamp: "2022-10-07T09:51:15Z"
  name: gitlab-access
  namespace: argo
  resourceVersion: "82779504"
  uid: 2073a94b-b7ff-44a5-be64-01808d12d832
type: Opaque
