apiVersion: es.eck.github.com/v1alpha1
kind: IndexTemplate
metadata:
  name: mda-logs-tmplt
spec:
  body: |
    {
      "index_patterns" : ["mda-logs-*"],
      "priority" : 1,
      "template": {
        "settings" : {
          "number_of_shards" : 2,
          "number_of_replicas" : 0,
          "index.lifecycle.name": "mda-logs-policy"
        },
        "mappings": {
           "enabled": false
         }
      }
    }
