
apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-configmap
  namespace: elastic-system
data:
  logstash.yml: |
    http.host: "0.0.0.0"
    path.config: /usr/share/logstash/pipeline
  logstash.conf: |
    # all input will come from filebeat, no local logs
    input {
      kafka{
        codec => json
        bootstrap_servers => "kafka-cluster-kafka-bootstrap-external-elastic:9092"
        topics => ["logs"]
      }
    }
    filter {
    }
    output {
      elasticsearch {
        index => "mda-logs-%{+YYYY-MM-dd}"
        hosts => [ "${ES_HOSTS}" ]
        user => "${ES_USER}"
        password => "${ES_PASSWORD}"
        ssl_certificate_verification => true
        cacert => '/etc/logstash/certificates/tls.crt'
      }
    }
