{{- if .Values.indexLifecyclePolicy.enabled -}}
{{- range .Values.indexLifecyclePolicy.policies }}
---
apiVersion: es.eck.github.com/v1alpha1
kind: IndexLifecyclePolicy
metadata:
  name: {{ .name }}
spec:
  body: |-
    {{- $.Files.Get (printf "%s" .filepath ) | nindent 6 -}}
{{- end }}
{{- end }}