{{- if .Values.indexPattern.enabled -}}
{{- range .Values.indexPattern.patterns }}
---
apiVersion: es.eck.github.com/v1alpha1
kind: IndexPattern
metadata:
  name: {{ .name }}
spec:
  space: {{ .spacename }}
  {{- with .dependencies }}
  dependencies:
    {{- toYaml . | nindent 8 }}
  {{- end }}

  body: {{ .body | toJson }}
{{- end }}
{{- end }}