{{- if .Values.indexPattern.enabled -}}
{{- range .Values.indexPattern.patterns }}
---
apiVersion: kibana.eck.github.com/v1alpha1
kind: IndexPattern
metadata:
  name: {{ .name }}
spec:
  space: {{ .spacename }}
  {{- with .dependencies }}
  dependencies:
    {{- toYaml . | nindent 8 }}
  {{- end }}

  body: |-
    {{- $.Files.Get (printf "%s" .filepath ) | nindent 6 -}}
{{- end }}
{{- end }}