{{- if .Values.index.enabled -}}
{{- range .Values.index.indeces }}
---
apiVersion: es.eck.github.com/v1alpha1
kind: Index
metadata:
  name: {{ .name }}
spec:
  {{- with .dependencies }}
  dependencies:
    {{- toYaml . | nindent 8 }}
  {{- end }}
  body: {{ .body | toJson }}
{{- end }}
{{- end }}