{{- if .Values.lens.enabled -}}
{{- range .Values.lens.lenses }}
---
apiVersion: kibana.eck.github.com/v1alpha1
kind: Lens
metadata:
  name: {{ .name }}
spec:
  space: {{ .spacename }}
  {{- with .dependencies }}
  dependencies:
    {{- toYaml . | nindent 8 }}
  {{- end }}

  body: |-
    {{- $.Files.Get (printf "%s" .filepath ) | nindent 6 -}}
{{- end }}
{{- end }}