{{- if .Values.role.enabled -}}
{{- range .Values.role.roles }}
---
apiVersion: es.eck.github.com/v1alpha1
kind: ElasticsearchRole
metadata:
  name: {{ .name }}
spec:
  body: |-
    {{- $.Files.Get (printf "%s" .filepath ) | nindent 6 -}}
{{- end }}
{{- end }}