{{- if .Values.space.enabled -}}
{{- range .Values.space.spaces }}
---
apiVersion: kibana.eck.github.com/v1alpha1
kind: Space
metadata:
  name: {{ .name }}
spec:
  body: |-
    {{- $.Files.Get (printf "%s" .filepath ) | nindent 6 -}}
{{- end }}
{{- end }}