{{- if .Values.visualization.enabled -}}
{{- range .Values.visualization.visualizations }}
---
apiVersion: kibana.eck.github.com/v1alpha1
kind: Visualization
metadata:
  name: {{ .name }}
spec:
  space: {{ .spacename }}
  {{- with .dependencies }}
  dependencies:
    {{- toYaml . | nindent 8 }}
  {{- end }}

  body: {{ .body | toJson }}
{{- end }}
{{- end }}