apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: logstashes.elasticsearch.k8s.elastic.co
spec:
  group: elasticsearch.k8s.elastic.co
  names:
    categories:
    - elastic
    kind: Logstash
    plural: logstashes
    singular: logstash
  scope: Namespaced
  versions:
    - name: v1
    served: true
    storage: true
    schema:
    #TODO Remove all values in the Following section and create a correct CRD-Template
      openAPIV3Schema:
        description: Logstash-CRD for using logstash as a stateful deployment.
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: LogstashSpec holds the specification of an Logstash cluster.
            properties:
              containers:
                description:
                items:
                    description: FileRealmSource references users to create in the Elasticsearch cluster.
                    properties:
                      secretName:
                        description: SecretName is the name of the secret.
                        type: string
                    type: object
                  type: array
                  - image: docker.elastic.co/logstash/logstash:8.3.3
                    name: logstash
                    ports:
                    - containerPort: 25826
                    - containerPort: 5044
                    env:
                    - name: ES_HOSTS
                      value: "https://elk-cluster-es-default:9200"
                    - name: ES_USER
                      value: "elastic"
                    - name: ES_PASSWORD
                      valueFrom:
                        secretKeyRef:
                          name: elk-cluster-es-elastic-user
                          key: elastic
                  resources: {}
                  volumeMounts:
                  - name: config-volume
                    mountPath: /usr/share/logstash/config
                  - name: logstash-pipeline-volume
                    mountPath: /usr/share/logstash/pipeline
                  - name: cert-ca
                    mountPath: "/etc/logstash/certificates"
                    readOnly: true

              restartPolicy:
                description: 
                type: string

              volumes:
                description:
                properties:
                  - name: config-volume
                    configMap:
                      name: logstash-configmap
                      items:
                        - key: logstash.yml
                          path: logstash.yml
                  - name: logstash-pipeline-volume
                    configMap:
                      name: logstash-configmap
                      items:
                        - key: logstash.conf
                          path: logstash.conf
                  - name: cert-ca
                    secret:
                      secretName: elk-cluster-es-http-certs-public
    