apiVersion: v1
kind: Namespace
metadata:
  name: victoriametrics
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vm-operator
  namespace: victoriametrics
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: vm-operator
  name: vm-operator
  namespace: victoriametrics
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: vm-operator
  template:
    metadata:
      labels:
        control-plane: vm-operator
    spec:
      containers:
      - args:
        - --enable-leader-election
        command:
        - manager
        env:
        - name: WATCH_NAMESPACE
          value: ""
        image: victoriametrics/operator:v0.26.3
        name: manager
        resources:
          limits:
            cpu: 120m
            memory: 520Mi
          requests:
            cpu: 80m
            memory: 120Mi
      serviceAccountName: vm-operator
      terminationGracePeriodSeconds: 10
