{
 "title": "VictoriaMetrics - cluster per tenant statistic via Slide car2",
 "description": "Per-tenant overview of Enterprise Cluster VictoriaMetrics v1.56.0 or higher ",
 "tags": [
  "VictoriaMetrics",
  "monitoring"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" },
   {
    "name": "job",
    "query": {
     "query": "label_values(vm_app_version{version=~\"^vm(insert|select|storage).*\"}, job)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(vm_app_version{job=~\"$job\"}, instance)"
    }
   },
   {
    "name": "account",
    "query": {
     "query": "label_values(vm_tenant_active_timeseries{job=~\"$job\"},accountID)"
    }
   },
   {
    "name": "project",
    "query": {
     "query": "label_values(vm_tenant_active_timeseries{accountID=~\"$accountID\"},projectID)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Datapoints ingestion rate ($instance)",
   "type": "graph",
   "description": "How many datapoints are inserted into storage per second by accountID and projectID",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(vm_tenant_inserted_rows_total{job=~\"$job\", instance=~\"$instance\",accountID=~\"$account\", projectID=~\"$project\"}[1m])/60) by (accountID,projectID) ",
     "legendFormat": "inserted rows: {{accountID}}:{{projectID}}"
    }
   ]
  },
  {
   "title": "Query rate ($instance)",
   "type": "graph",
   "description": "Request rate accepted by vmselect nodes per tenant",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vm_tenant_select_requests_total{job=~\"$job\", instance=~\"$instance.*\",accountID=~\"$account\", projectID=~\"$project\"}[$__rate_interval])) by (accountID,projectID) ",
     "legendFormat": "query rate tenant: {{accountID}}:{{projectID}}"
    }
   ]
  },
  {
   "title": "Active time series ($instance)",
   "type": "graph",
   "description": "Shows the number of active time series with new data points inserted during the last hour. High value may result in ingestion slowdown. \n\nSee following link for details:",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(vm_tenant_active_timeseries{job=~\"$job\", instance=~\"$instance.*\",accountID=~\"$account\",projectID=~\"$project\"}) by(accountID,projectID)",
     "legendFormat": "Active time series tenant: {{accountID}}:{{projectID}}"
    }
   ]
  },
  {
   "title": "Churn rate ($instance)",
   "type": "graph",
   "description": "Shows how many of new time-series are created every second.  High churn rate tightly connected with database performance and may result in unexpected OOM's or slow queries. It is recommended to always keep an eye on this metric to avoid unexpected cardinality \"explosions\".\n\nGood references to read:\n* https://www.robustperception.io/cardinality-is-key\n* https://www.robustperception.io/using-tsdb-analyze-to-investigate-churn-and-cardinality",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(vm_tenant_timeseries_created_total{job=~\"$job\", instance=~\"$instance\",accountID=~\"$account\", projectID=~\"$project\"}[1m])/60) by(accountID,projectID)",
     "legendFormat": "churn rate tenant: {{accountID}}:{{projectID}}"
    }
   ]
  },
  {
   "title": "Disk space usage (datapoints) ($instance)",
   "type": "graph",
   "description": "Shows amount of on-disk space occupied by data points.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(vm_tenant_used_tenant_bytes{job=~\"$job\", instance=~\"$instance\",accountID=~\"$account\",projectID=~\"$project\"}) by(accountID,projectID)",
     "legendFormat": "disk usage tenant {{accountID}}:{{projectID}}"
    }
   ]
  }
 ]
}