apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "ecc.fullname" . }}
  labels:
    {{- include "ecc.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      # Deployment affects PODs with following labels
      {{- include "ecc.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "ecc.fullname" . }}-headless
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ecc.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ecc.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      restartPolicy: Always
      containers:
        - name: {{ include "ecc.name" . }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: APPL_ENVIRONMENT_PATH
              value: "/etc/secret-volume/environment.conf"
            - name: APPL_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          volumeMounts:
            # name must match the volume name below
            - name: {{ include "ecc.name" . }}-shared-logs
              mountPath: /home/platform/log

            - name: {{ include "ecc.name" . }}-secret-volume
              mountPath: /etc/secret-volume/
              readOnly: true

        - name: fluentbit
          image: alpine:latest
          command: ["sh", "-c", " echo \"Fluentbit ${HOSTNAME}\"; while [ 1 ]; do ls -al /home/platform/log; sleep 300; done;"]
          volumeMounts:
            # name must match the volume name below
            - name: {{ include "ecc.name" . }}-shared-logs
              mountPath: /home/platform/log
      volumes:
        - name: {{ include "ecc.name" . }}-shared-logs
          emptyDir: {}
        - name: {{ include "ecc.name" . }}-secret-volume
          secret:
            secretName: {{ include "ecc.fullname" . }}-secret

