apiVersion: v1
kind: Service
metadata:
  name: rcdb-nodeport
spec:
  type: NodePort
  ports:
    - nodePort: 30100
      targetPort: 8000
      port: 8000
      name: rcdb
  selector:
    # Deployment affects PODs with following labels
    app: gcc
    tier: rcdb
