---
apiVersion: v1
kind: Secret
metadata:
  name: atosregistrykey
  namespace: api
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJyZWdpc3RyeS5naXRsYWIuY29tIjogewoJCQkiYXV0aCI6ICJZWFJ2YzJkeWIzVndPbmR6UmprMmMwWjZRWFZRZVhaSGNWaDFkSFpCIgoJCX0KCX0KfQ==
type: kubernetes.io/dockerconfigjson
