---
apiVersion: v1
kind: Secret
metadata:
{{- with (index .Values.imagePullSecrets 0) }}
  name: {{ .name }}
{{- end }}
  namespace: api
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
type: kubernetes.io/dockerconfigjson
