apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlert
metadata:
  name: vmalert
  namespace: victoriametrics
spec:
  replicaCount: 1
  datasource:
    url: "http://vmstorage-vmcluster-persistent-0:8429"
  notifier:
      url: "http://vmalertmanager-alertmanager-0:9093"
  evaluationInterval: "30s"
  selectAllByDefault: true