apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlert
metadata:
  name: vmalert
  namespace: victoriametrics
spec:
  replicaCount: 1
  datasource:
    url: "http://vmcluster-vmcluster-persisted.default.svc:8429"
  notifier:
      url: "http://vmalertmanager-alertmanager.default.svc:9093"
  evaluationInterval: "30s"
  selectAllByDefault: true