{{- if .Values.configmap.enabled -}}
{{- if .Values.daemonset.enabled -}}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    k8s-app: {{ .Release.Name }}
spec:
  {{- toYaml .Values.daemonset.spec | nindent 2 }}

{{- end }}
{{- end }}