{{- if or .Values.autodiscover.enabled .Values.configmap.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: filebeat
  namespace: {{ .Release.Namespace }}
  labels:
    k8s-app: {{ .Release.Name }}
{{- end }}