---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: atosspain
  namespace: gcc
spec:
  interval: 10s
  ref:
    branch: main
  secretRef:
    name: podinfo-auth1
    namespace: flux-system 
  url: ssh://git@gitlab.com/swapnil743/fluxcd-demo.git
