---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: atosspain-rcdb-release
  namespace: gcc
spec:
  chart:
    spec:
      chart: ./cluster/charts/rcdb/helm
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: podinfo 
        namespace: flux-system 
  interval: 1m0s
  releaseName: atosspain-rcdb-release

