---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: my-release
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ./cluster/podinfo/helm
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: podinfo
  interval: 1m0s
  releaseName: my-release

