---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 10s
  ref:
    branch: main
  secretRef:
    name: podinfo-auth1
  url: ssh://git@gitlab.com/swapnil743/fluxcd-demo.git

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 10s
  path: ./cluster/fluxcd/flux-system
  prune: true
  sourceRef:
    kind: GitRepository
    name: podinfo

