apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  finalizers:
  - eventsource-controller
  name: kafka
  namespace: argo
spec:
  kafka:
    example:
      connectionBackoff:
        duration: 10s
        factor: 2
        jitter: 0.2
        steps: 5
      jsonBody: true
      partition: 0
    example2:
      connectionBackoff:
        duration: 10s
        factor: 2
        jitter: 0.2
        steps: 5
      jsonBody: true
      partition: 1
    example3:
      connectionBackoff:
        duration: 10s
        factor: 2
        jitter: 0.2
        steps: 5
      jsonBody: true
      partition: 2

      topic: python_test
      url: kafka.kafka:9092