apiVersion: v1
kind: Secret
metadata:
    name: {{ include "rc.fullname" . }}-secret
type: Opaque
stringData:
    environment.conf: |
      __SSA_HOST__=localhost
      __DS1_HOST__={{ .Values.rcdbNodeportServiceName }}.{{ .Values.rcdbNamespace }}.svc.cluster.local
      __DS_PORT__={{ .Values.rcdbNodeportServicePort }}
      __PROPAGATE_HOST_LIST__=localhost
      __PROPAGATE_PROC_LIST__=ifDataStore_1

