# Default values for api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

# imageCredentials:
#   registry: harbor.berlindevops.com
#   username: robot$cicd
#   password: mQWtz5HJAOSneL11Nda5povEKGeQZmdP
#   email: atosnet@berlindevops.com
imageCredentials:
  registry: registry.gitlab.com
  username: swapnil743 
  password: YH3EytezZY3xpyKKHqzn 
  email: atosnet@berlindevops.com

# image:
#   repository: harbor.berlindevops.com/aac/api
#   pullPolicy: Always
#   # Overrides the image tag whose default is the chart appVersion.
#   tag: latest
image:
  repository: registry.gitlab.com/atosnet/cb-fastapi
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  # tag: latest
  tag: 7fdc5ed

imagePullSecrets:
  - name: atosregistrykey
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "cb-fastapi"

apiClusterRole: cb-fastapi-role-cluster

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: true
  className: nginx
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: gitlab-webhook.cicd.berlindevops.com
      paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: cb-fastapi
              port:
                number: 8000

  tls:
    - hosts:
        - gitlab-webhook.cicd.berlindevops.com
      secretName: cb-fastapi-tls

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

extraEnvVars: []
  # - name: REDIS_HOST
  #   value: "redis-master.redisgraph.svc.cluster.local"
  # - name: REDIS_PORT
  #   value: "6379"
  # - name: REDIS_GRAPH
  #   value: "atoscrd"
  # - name: REDIS_PASSWORD
  #   value: "gMGNEFh9FY"
