persistence:
  enabled: true

logstashConfig:
  logstash.yml: |
    http.host: 0.0.0.0
    xpack.monitoring.enabled: false

logstashPipeline:
  uptime.conf: |
    input {
      kafka {
        codec => json
        bootstrap_servers => "kafka.kafka.svc.cluster.local:9092"
        topics => ["logs"]
      }
    }
    output {
      elasticsearch {
        index => "mda-logs-%{+YYYY-MM-dd}"
        hosts => ["http://elastic-eck-elasticsearch-es-http:9200"]
        user => "elastic"
        password => "${ELASTICSEARCH_PASSWORD}"
        ssl => false
        ssl_certificate_verification => false
        cacert => '/usr/share/logstash/config/certs'
      }
    }

extraEnvs:
  #- name: "ELASTICSEARCH_USERNAME"
  #  valueFrom:
  #    secretKeyRef:
  #      name: elasticsearch-master-credentials
  #      key: username
  - name: "ELASTICSEARCH_PASSWORD"
    valueFrom:
      secretKeyRef:
        name: elastic-eck-elasticsearch-es-elastic-user
        key: elastic

secretMounts: 
  - name: elasticsearch-master-certs
    secretName: elastic-eck-elasticsearch-es-http-certs-public
    path: /usr/share/logstash/config/certs
