apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-services
  namespace: ingress-nginx
data:
  9094: "kafka/kafka:9092"
---
apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
spec:
  type: ClusterIP
  ports:
    - name: proxied-tcp-9094
      port: 9094
      targetPort: 9094
      protocol: TCP
  selector:
    app.kubernetes.io/component: controller  
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx      