space:
  enabled: true
  spaces:
    - name: space-sample
      body: |
        {
            "name": "ECK Space sample",
            "description" : "This space was created using ECK-CR operator",
            "color": "#aabbcc",
            "initials": "CR",
            "disabledFeatures": [],
            "imageUrl": ""
        }

indexLifecyclePolicy:
  enabled: true
  policies:
    - name: mda-logs-policy
      body: |
        {
          "policy": {
            "phases": {
              "hot": {
                "actions": {
                  "rollover" : {
                    "max_age": "1d"
                  }
                }
              },                
              "delete": {
                "min_age": "2d",
                "actions": {
                  "delete": {}
                }
              }
            }
          }
        }

indexTemplate:
  enabled: true
  templates:
    - name: mda-logs-tmplt
      body: |
        {
          "index_patterns" : ["mda-logs-*"],
          "priority" : 1,
          "template": {
            "settings" : {
              "number_of_shards" : 2,
              "number_of_replicas" : 0,
              "index.lifecycle.name": "mda-logs-policy"
            },
            "mappings": {
              "enabled": true
            }
          }
        }

    - name: indextemplate-sample
      body: |
        {
          "index_patterns" : ["index-*"],
          "priority" : 1,
          "template": {
            "settings" : {
              "number_of_shards" : 2,
              "number_of_replicas" : 0
            }
          }
        }


index:
  enabled: true
  indeces:
    - name: index-sample
      dependencies:
        indexTemplates:
          - indextemplate-sample
        #indices:
        #  - index-base-sample
      body: |
          {
            "settings": {
              "number_of_shards": 1,
              "number_of_replicas": 0
            },
            "mappings": {
                "properties": {
                  "field1": { "type": "text" }
                }
            },
            "aliases": {
                "index-sample-alias": {}
            }
          }

indexPattern:
  enabled: true
  patterns:
    - name: indexpattern-sample
      spacename: space-sample 
      #dependencies:
      #  - type: index-pattern
      #    name: indexpattern-base-sample
      body: |
        {
            "attributes": {
                "title": "index-*",
                "timeFieldName": "@timestamp"
            }
        }

savedSearch:
  enabled: true
  searches:
    - name: savedsearch-sample
      spacename:  space-sample
      dependencies:
        - type: index-pattern
          name: indexpattern-sample
      body: |
          {
            "attributes": {
              "columns": [
                  "_source"
              ],
              "description": "",
              "hits": 0,
              "kibanaSavedObjectMeta": {
                  "searchSourceJSON": "{\"highlightAll\":true,\"version\":true,\"query\":{\"query\":\"(message: test)\",\"language\":\"kuery\"},\"filter\":[],\"indexRefName\":\"kibanaSavedObjectMeta.searchSourceJSON.index\"}"
              },
              "sort": [],
              "title": "Message contains test",
              "version": 1
            },
            "references": [
              {
                  "id": "indexpattern-sample",
                  "name": "kibanaSavedObjectMeta.searchSourceJSON.index",
                  "type": "index-pattern"
              }
            ]
          }

visualization:
  enabled: true
  visualizations:
    - name: visualization-sample
      spacename:  space-sample
      dependencies:
        - type: index-pattern
          name: indexpattern-sample
      body: |
        {
          "attributes": {
            "visState": "{\"title\":\"Count visualization\",\"type\":\"metric\",\"aggs\":[{\"id\":\"1\",\"enabled\":true,\"type\":\"count\",\"params\":{},\"schema\":\"metric\"}],\"params\":{\"addTooltip\":true,\"addLegend\":false,\"type\":\"metric\",\"metric\":{\"percentageMode\":false,\"useRanges\":false,\"colorSchema\":\"Green to Red\",\"metricColorMode\":\"None\",\"colorsRange\":[{\"from\":0,\"to\":10000}],\"labels\":{\"show\":true},\"invertColors\":false,\"style\":{\"bgFill\":\"#000\",\"bgColor\":false,\"labelColor\":false,\"subText\":\"\",\"fontSize\":60}}}}",
            "title": "Count visualization",
            "uiStateJSON": "{}",
            "description": "",
            "version": 1,
            "kibanaSavedObjectMeta": {
              "searchSourceJSON": "{\"query\":{\"query\":\"\",\"language\":\"kuery\"},\"filter\":[],\"indexRefName\":\"kibanaSavedObjectMeta.searchSourceJSON.index\"}"
            }
          },
          "references": [
            {
              "name": "kibanaSavedObjectMeta.searchSourceJSON.index",
              "type": "index-pattern",
              "id": "indexpattern-sample"
            }
          ]
        }

lens:
  enabled: true
  lenses:
    - name: lens-sample
      spacename:  space-sample
      dependencies:
        - type: index-pattern
          name: indexpattern-sample
      body: |
          {
            "attributes": {
              "title": "Count of docs 2",
              "description": "",
              "visualizationType": "lnsMetric",
              "state": {
                "visualization": {
                  "layerId": "13e00170-fe50-4495-87ff-048934afece1",
                  "accessor": "6d115d38-e79d-4e91-b5c2-29a69065cbfc",
                  "layerType": "data"
                },
                "query": {
                  "query": "",
                  "language": "kuery"
                },
                "filters": [],
                "datasourceStates": {
                  "indexpattern": {
                    "layers": {
                      "13e00170-fe50-4495-87ff-048934afece1": {
                        "columns": {
                          "6d115d38-e79d-4e91-b5c2-29a69065cbfc": {
                            "label": "Count of records",
                            "dataType": "number",
                            "operationType": "count",
                            "isBucketed": false,
                            "scale": "ratio",
                            "sourceField": "___records___"
                          }
                        },
                        "columnOrder": [
                            "6d115d38-e79d-4e91-b5c2-29a69065cbfc"
                        ],
                        "incompleteColumns": {}
                      }
                    }
                  }
                }
              }
            },
            "references": [
              {
                "type": "index-pattern",
                "id": "indexpattern-sample",
                "name": "indexpattern-datasource-current-indexpattern"
              },
              {
                "type": "index-pattern",
                "id": "indexpattern-sample",
                "name": "indexpattern-datasource-layer-13e00170-fe50-4495-87ff-048934afece1"
              }
            ]
          }

dashboard:
  enabled: true
  dashboards:
    - name: dashboard-sample
      spacename:  space-sample
      dependencies:
        - type: lens
          name: lens-sample
      body: |
        {
          "attributes": {
            "title": "Sample dashboard",
            "hits": 0,
            "description": "",
            "panelsJSON": "[{\"version\":\"8.1.0\",\"type\":\"lens\",\"gridData\":{\"x\":0,\"y\":0,\"w\":24,\"h\":15,\"i\":\"4cfcdf6b-1729-4467-a911-c69be15d58f8\"},\"panelIndex\":\"4cfcdf6b-1729-4467-a911-c69be15d58f8\",\"embeddableConfig\":{\"enhancements\":{}},\"panelRefName\":\"panel_4cfcdf6b-1729-4467-a911-c69be15d58f8\"}]",
            "optionsJSON": "{\"useMargins\":true,\"syncColors\":false,\"hidePanelTitles\":false}",
            "version": 1,
            "timeRestore": false,
            "kibanaSavedObjectMeta": {
              "searchSourceJSON": "{\"query\":{\"query\":\"\",\"language\":\"kuery\"},\"filter\":[]}"
            }
          },
          "references": [
            {
              "name": "4cfcdf6b-1729-4467-a911-c69be15d58f8:panel_4cfcdf6b-1729-4467-a911-c69be15d58f8",
              "type": "lens",
              "id": "lens-sample"
            }
          ]
        }

    - name: "[MDA][Fluentd]Lens for kubernetes.container_name"
      spacename:  default
      body: |
        {"attributes":{"fieldAttrs":"{}","fields":"[]","name":"mda-logs-*","runtimeFieldMap":"{}","sourceFilters":"[]","timeFieldName":"@timestamp","title":"mda-logs-*","typeMeta":"{}"},"coreMigrationVersion":"8.4.1","id":"a4d07e64-1c19-407c-a281-96eeb9def3cd","migrationVersion":{"index-pattern":"8.0.0"},"references":[],"type":"index-pattern","updated_at":"2022-10-21T07:04:53.444Z","version":"WzEwNiwxXQ=="}
        {"attributes":{"description":"","hits":0,"kibanaSavedObjectMeta":{"searchSourceJSON":"{\"query\":{\"query\":\"\",\"language\":\"kuery\"},\"filter\":[]}"},"optionsJSON":"{\"useMargins\":true,\"syncColors\":false,\"syncTooltips\":false,\"hidePanelTitles\":false}","panelsJSON":"[{\"version\":\"8.4.1\",\"type\":\"lens\",\"gridData\":{\"x\":0,\"y\":0,\"w\":48,\"h\":21,\"i\":\"dc069ffc-0f57-4ca3-a859-f8cba4d44fac\"},\"panelIndex\":\"dc069ffc-0f57-4ca3-a859-f8cba4d44fac\",\"embeddableConfig\":{\"attributes\":{\"title\":\"[MDA][Fluentd]Lens for kubernetes.container_name\",\"description\":\"\",\"visualizationType\":\"lnsPie\",\"type\":\"lens\",\"references\":[{\"type\":\"index-pattern\",\"id\":\"a4d07e64-1c19-407c-a281-96eeb9def3cd\",\"name\":\"indexpattern-datasource-layer-layer1\"}],\"state\":{\"visualization\":{\"shape\":\"donut\",\"layers\":[{\"layerId\":\"layer1\",\"groups\":[\"col1\"],\"metric\":\"col2\",\"numberDisplay\":\"percent\",\"categoryDisplay\":\"default\",\"legendDisplay\":\"default\",\"nestedLegend\":false,\"layerType\":\"data\"}]},\"query\":{\"language\":\"kuery\",\"query\":\"\"},\"filters\":[],\"datasourceStates\":{\"indexpattern\":{\"layers\":{\"layer1\":{\"columnOrder\":[\"col1\",\"col2\"],\"columns\":{\"col1\":{\"label\":\"Top values\",\"dataType\":\"string\",\"isBucketed\":true,\"operationType\":\"terms\",\"params\":{\"orderBy\":{\"type\":\"column\",\"columnId\":\"col2\"},\"size\":10,\"orderDirection\":\"desc\"},\"sourceField\":\"kubernetes.container_name.keyword\"},\"col2\":{\"label\":\"Count\",\"dataType\":\"number\",\"isBucketed\":false,\"sourceField\":\"___records___\",\"operationType\":\"count\"}}}}}}}},\"enhancements\":{}}}]","timeRestore":false,"title":"[MDA][Fluentd]Lens for kubernetes.container_name","version":1},"coreMigrationVersion":"8.4.1","id":"c8212d10-5242-11ed-b78a-c7d840dd7e4e","migrationVersion":{"dashboard":"8.4.0"},"references":[{"id":"a4d07e64-1c19-407c-a281-96eeb9def3cd","name":"dc069ffc-0f57-4ca3-a859-f8cba4d44fac:indexpattern-datasource-layer-layer1","type":"index-pattern"}],"type":"dashboard","updated_at":"2022-10-22T19:50:29.736Z","version":"Wzg5OTQsMV0="}
        {"excludedObjects":[],"excludedObjectsCount":0,"exportedCount":2,"missingRefCount":0,"missingReferences":[]}


    - name: "[MDA][Fluentd]Lens for kubernetes.pod_name"
      spacename:  default
      body: |
        {"attributes":{"fieldAttrs":"{}","fields":"[]","name":"mda-logs-*","runtimeFieldMap":"{}","sourceFilters":"[]","timeFieldName":"@timestamp","title":"mda-logs-*","typeMeta":"{}"},"coreMigrationVersion":"8.4.1","id":"a4d07e64-1c19-407c-a281-96eeb9def3cd","migrationVersion":{"index-pattern":"8.0.0"},"references":[],"type":"index-pattern","updated_at":"2022-10-21T07:04:53.444Z","version":"WzEwNiwxXQ=="}
        {"attributes":{"description":"","hits":0,"kibanaSavedObjectMeta":{"searchSourceJSON":"{\"query\":{\"query\":\"\",\"language\":\"kuery\"},\"filter\":[]}"},"optionsJSON":"{\"useMargins\":true,\"syncColors\":false,\"syncTooltips\":false,\"hidePanelTitles\":false}","panelsJSON":"[{\"version\":\"8.4.1\",\"type\":\"lens\",\"gridData\":{\"x\":0,\"y\":0,\"w\":48,\"h\":20,\"i\":\"d8193d92-bf58-4bcb-be54-e3b5445e85d7\"},\"panelIndex\":\"d8193d92-bf58-4bcb-be54-e3b5445e85d7\",\"embeddableConfig\":{\"attributes\":{\"title\":\"[MDA][Fluentd]Lens for kubernetes.pod_name.keyword\",\"description\":\"\",\"visualizationType\":\"lnsPie\",\"type\":\"lens\",\"references\":[{\"type\":\"index-pattern\",\"id\":\"a4d07e64-1c19-407c-a281-96eeb9def3cd\",\"name\":\"indexpattern-datasource-layer-layer1\"}],\"state\":{\"visualization\":{\"shape\":\"donut\",\"layers\":[{\"layerId\":\"layer1\",\"groups\":[\"col1\"],\"metric\":\"col2\",\"numberDisplay\":\"percent\",\"categoryDisplay\":\"default\",\"legendDisplay\":\"default\",\"nestedLegend\":false,\"layerType\":\"data\"}]},\"query\":{\"language\":\"kuery\",\"query\":\"\"},\"filters\":[],\"datasourceStates\":{\"indexpattern\":{\"layers\":{\"layer1\":{\"columnOrder\":[\"col1\",\"col2\"],\"columns\":{\"col1\":{\"label\":\"Top values\",\"dataType\":\"string\",\"isBucketed\":true,\"operationType\":\"terms\",\"params\":{\"orderBy\":{\"type\":\"column\",\"columnId\":\"col2\"},\"size\":10,\"orderDirection\":\"desc\"},\"sourceField\":\"kubernetes.pod_name.keyword\"},\"col2\":{\"label\":\"Count\",\"dataType\":\"number\",\"isBucketed\":false,\"sourceField\":\"___records___\",\"operationType\":\"count\"}}}}}}}},\"enhancements\":{}}}]","timeRestore":false,"title":"[MDA][Fluentd]Lens for kubernetes.pod_name","version":1},"coreMigrationVersion":"8.4.1","id":"b3b6ffe0-5241-11ed-b78a-c7d840dd7e4e","migrationVersion":{"dashboard":"8.4.0"},"references":[{"id":"a4d07e64-1c19-407c-a281-96eeb9def3cd","name":"d8193d92-bf58-4bcb-be54-e3b5445e85d7:indexpattern-datasource-layer-layer1","type":"index-pattern"}],"type":"dashboard","updated_at":"2022-10-22T19:42:45.995Z","version":"Wzg5MDIsMV0="}
        {"excludedObjects":[],"excludedObjectsCount":0,"exportedCount":2,"missingRefCount":0,"missingReferences":[]}

    - name: "[MDA][Filebeat]Lens for kubernetes.container.name"
      spacename:  default
      body: |
        {"attributes":{"fieldAttrs":"{}","fields":"[]","name":"mda-logs-*","runtimeFieldMap":"{}","sourceFilters":"[]","timeFieldName":"@timestamp","title":"mda-logs-*","typeMeta":"{}"},"coreMigrationVersion":"8.4.1","id":"a4d07e64-1c19-407c-a281-96eeb9def3cd","migrationVersion":{"index-pattern":"8.0.0"},"references":[],"type":"index-pattern","updated_at":"2022-10-21T07:04:53.444Z","version":"WzEwNiwxXQ=="}
        {"attributes":{"description":"","hits":0,"kibanaSavedObjectMeta":{"searchSourceJSON":"{\"query\":{\"query\":\"\",\"language\":\"kuery\"},\"filter\":[]}"},"optionsJSON":"{\"useMargins\":true,\"syncColors\":false,\"syncTooltips\":false,\"hidePanelTitles\":false}","panelsJSON":"[{\"version\":\"8.4.1\",\"type\":\"lens\",\"gridData\":{\"x\":0,\"y\":0,\"w\":48,\"h\":21,\"i\":\"eb499ae1-e9df-4d08-85db-3fdf811997a0\"},\"panelIndex\":\"eb499ae1-e9df-4d08-85db-3fdf811997a0\",\"embeddableConfig\":{\"attributes\":{\"title\":\"[MDA][Filebeat]Lens for kubernetes.container.name\",\"description\":\"\",\"visualizationType\":\"lnsPie\",\"type\":\"lens\",\"references\":[{\"type\":\"index-pattern\",\"id\":\"a4d07e64-1c19-407c-a281-96eeb9def3cd\",\"name\":\"indexpattern-datasource-layer-layer1\"}],\"state\":{\"visualization\":{\"shape\":\"donut\",\"layers\":[{\"layerId\":\"layer1\",\"groups\":[\"col1\"],\"metric\":\"col2\",\"numberDisplay\":\"percent\",\"categoryDisplay\":\"default\",\"legendDisplay\":\"default\",\"nestedLegend\":false,\"layerType\":\"data\"}]},\"query\":{\"language\":\"kuery\",\"query\":\"\"},\"filters\":[],\"datasourceStates\":{\"indexpattern\":{\"layers\":{\"layer1\":{\"columnOrder\":[\"col1\",\"col2\"],\"columns\":{\"col1\":{\"label\":\"Top values\",\"dataType\":\"string\",\"isBucketed\":true,\"operationType\":\"terms\",\"params\":{\"orderBy\":{\"type\":\"column\",\"columnId\":\"col2\"},\"size\":10,\"orderDirection\":\"desc\"},\"sourceField\":\"kubernetes.container.name.keyword\"},\"col2\":{\"label\":\"Count\",\"dataType\":\"number\",\"isBucketed\":false,\"sourceField\":\"___records___\",\"operationType\":\"count\"}}}}}}}},\"enhancements\":{}}}]","timeRestore":false,"title":"[MDA][Filebeat]Lens for kubernetes.container.name","version":1},"coreMigrationVersion":"8.4.1","id":"495dd220-5112-11ed-b78a-c7d840dd7e4e","migrationVersion":{"dashboard":"8.4.0"},"references":[{"id":"a4d07e64-1c19-407c-a281-96eeb9def3cd","name":"eb499ae1-e9df-4d08-85db-3fdf811997a0:indexpattern-datasource-layer-layer1","type":"index-pattern"}],"type":"dashboard","updated_at":"2022-10-21T07:30:50.057Z","version":"WzM3NiwxXQ=="}
        {"excludedObjects":[],"excludedObjectsCount":0,"exportedCount":2,"missingRefCount":0,"missingReferences":[]}

role:
  enabled: true
  roles:
    - name: elasticsearchrole-sample
      body: |
        {
          "cluster": ["all"],
          "indices": [
            {
              "names": [ "index-sample"],
              "privileges": ["all"]
            }
          ],
          "metadata" : {
            "version" : 1
          }
        }

user:
  enabled: true
  users:
    - name: elasticsearchuser-sample
      secretname: elasticsearchuser-secret
      password: dGVzdGVy
      body: |
        {
          "roles" : [ "kibana_admin", "elasticsearchrole-sample" ],
          "full_name" : "Manual tester",
          "email" : "manual.tester@gmail.com",
          "metadata" : {
            "intelligence" : 7
          }
        }

